import type { StackOptions } from "../types.js";
import { STACK_VERSIONS } from "../constants.js";
import { json, write } from "../utils/filesystem.js";

export async function generateBackend(o: StackOptions): Promise<void> {
  if (o.backend === "go") return go(o);
  return nest(o);
}
async function go(o: StackOptions): Promise<void> {
  const root = o.targetDir,
    b = "apps/api";
  await write(root, `${b}/go.mod`, `module ${o.goModule}\n\ngo 1.24\n`);
  await write(
    root,
    `${b}/.env.example`,
    `API_PORT=8080\n${o.database !== "none" ? "DATABASE_URL=change-me\n" : ""}${o.cache === "redis" ? "REDIS_URL=redis://localhost:6379\n" : ""}`
  );
  await write(
    root,
    `${b}/cmd/api/main.go`,
    `package main

import ("context"; "log/slog"; "net/http"; "os"; "os/signal"; "syscall"; "time"; "${o.goModule}/internal/router")
func main() { port := os.Getenv("API_PORT"); if port == "" { port = "8080" }; r := router.New(); server := &http.Server{Addr: ":" + port, Handler: r}; go func() { slog.Info("API listening", "port", port); if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed { slog.Error("server failed", "error", err); os.Exit(1) } }(); signals := make(chan os.Signal, 1); signal.Notify(signals, syscall.SIGINT, syscall.SIGTERM); <-signals; ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second); defer cancel(); _ = server.Shutdown(ctx) }
`
  );
  await write(
    root,
    `${b}/internal/router/router.go`,
    `package router
import ("net/http"; "github.com/gin-gonic/gin"; "${o.goModule}/internal/handler")
func New() *gin.Engine { r := gin.New(); r.Use(gin.Logger(), gin.Recovery()); h := handler.NewUserHandler(nil); r.GET("/health", func(c *gin.Context) { c.JSON(http.StatusOK, gin.H{"success": true, "message": "API is running", "data": gin.H{"status": "healthy"}}) }); v1 := r.Group("/api/v1"); v1.GET("/status", func(c *gin.Context) { c.JSON(http.StatusOK, gin.H{"success": true, "message": "API is running", "data": gin.H{"status": "healthy"}}) }); v1.GET("/users", h.List); return r }
`
  );
  await write(
    root,
    `${b}/internal/model/user.go`,
    'package model\ntype User struct { ID uint `json:"id" gorm:"primaryKey"`; Name string `json:"name"`; Email string `json:"email"` }\n'
  );
  await write(
    root,
    `${b}/internal/repository/user_repository.go`,
    `package repository\nimport "${o.goModule}/internal/model"\ntype UserRepository interface { List() ([]model.User, error) }\n`
  );
  await write(
    root,
    `${b}/internal/service/user_service.go`,
    `package service\nimport ("${o.goModule}/internal/model"; "${o.goModule}/internal/repository")\ntype UserService interface { List() ([]model.User, error) }; type userService struct { repo repository.UserRepository }; func NewUserService(repo repository.UserRepository) UserService { return &userService{repo} }; func (s *userService) List() ([]model.User, error) { if s.repo == nil { return []model.User{}, nil }; return s.repo.List() }\n`
  );
  await write(
    root,
    `${b}/internal/handler/user_handler.go`,
    `package handler\nimport ("net/http"; "github.com/gin-gonic/gin"; "${o.goModule}/internal/service")\ntype UserHandler struct { service service.UserService }; func NewUserHandler(s service.UserService) *UserHandler { return &UserHandler{s} }; func (h *UserHandler) List(c *gin.Context) { users := []any{}; if h.service != nil { result, err := h.service.List(); if err != nil { c.JSON(500, gin.H{"success":false,"message":"failed to get users"}); return }; for _, user := range result { users = append(users, user) } }; c.JSON(http.StatusOK, gin.H{"success":true,"message":"Users retrieved","data":users}) }\n`
  );
  await write(
    root,
    `${b}/pkg/response/response.go`,
    'package response\ntype Response[T any] struct { Success bool `json:"success"`; Message string `json:"message"`; Data T `json:"data"` }\n'
  );
  for (const f of [
    "internal/config",
    "internal/database",
    "internal/middleware",
    "internal/validator",
    "pkg/utils",
    "migrations",
  ])
    await write(root, `${b}/${f}/.gitkeep`, "");
  await write(
    root,
    `${b}/README.md`,
    "# API\n\nGo + Gin service generated by StackBuild.\n"
  );
}
async function nest(o: StackOptions): Promise<void> {
  const root = o.targetDir,
    b = "apps/api";
  const prisma = o.database !== "none";
  await json(root, `${b}/package.json`, {
    name: "@stackbuild/api",
    private: true,
    version: "0.1.0",
    scripts: {
      start: "nest start",
      dev: "nest start --watch",
      build: "nest build",
      lint: 'eslint "src/**/*.ts"',
      typecheck: "tsc --noEmit",
      ...(prisma
        ? {
            "prisma:generate": "prisma generate",
            "prisma:migrate": "prisma migrate dev",
          }
        : {}),
    },
    dependencies: {
      "@nestjs/common": STACK_VERSIONS.nest,
      "@nestjs/config": STACK_VERSIONS.nestConfig,
      "@nestjs/core": STACK_VERSIONS.nest,
      "@nestjs/platform-express": STACK_VERSIONS.nest,
      "@nestjs/swagger": STACK_VERSIONS.nestSwagger,
      "class-transformer": "latest",
      "class-validator": "latest",
      "reflect-metadata": "latest",
      rxjs: "latest",
      ...(prisma ? { "@prisma/client": STACK_VERSIONS.prisma } : {}),
      ...(o.cache === "redis" ? { ioredis: STACK_VERSIONS.ioredis } : {}),
    },
    devDependencies: {
      "@nestjs/cli": STACK_VERSIONS.nestCli,
      "@nestjs/schematics": STACK_VERSIONS.nestSchematics,
      "@nestjs/testing": STACK_VERSIONS.nest,
      "@types/node": "latest",
      prisma: prisma ? STACK_VERSIONS.prisma : undefined,
      typescript: STACK_VERSIONS.typescript,
    },
  });
  await write(
    root,
    `${b}/.env.example`,
    `API_PORT=8080\n${prisma ? `DATABASE_URL=${o.database === "postgres" ? "postgresql://postgres:postgres@localhost:5432/app" : o.database === "mysql" ? "mysql://root:root@localhost:3306/app" : "file:./dev.db"}\n` : ""}${o.cache === "redis" ? "REDIS_URL=redis://localhost:6379\n" : ""}`
  );
  await write(
    root,
    `${b}/nest-cli.json`,
    '{ "collection": "@nestjs/schematics", "sourceRoot": "src" }\n'
  );
  await write(
    root,
    `${b}/tsconfig.json`,
    '{ "compilerOptions": { "module": "Node16", "moduleResolution": "node16", "declaration": true, "strict": true, "target": "ESNext", "lib": ["ESNext"], "esModuleInterop": true, "skipLibCheck": true, "experimentalDecorators": true, "emitDecoratorMetadata": true, "sourceMap": true, "rootDir": "./src", "outDir": "./dist" } }\n'
  );
  await write(
    root,
    `${b}/tsconfig.build.json`,
    '{ "extends": "./tsconfig.json", "exclude": ["node_modules", "test", "dist"] }\n'
  );
  await write(
    root,
    `${b}/src/main.ts`,
    `import { RequestMethod, ValidationPipe } from '@nestjs/common'; import { NestFactory } from '@nestjs/core'; import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger'; import { AppModule } from './app.module'; async function bootstrap() { const app = await NestFactory.create(AppModule); app.enableCors(); app.setGlobalPrefix('api/v1', { exclude: [{ path: 'health', method: RequestMethod.GET }] }); app.useGlobalPipes(new ValidationPipe({ transform: true, whitelist: true })); const doc = SwaggerModule.createDocument(app, new DocumentBuilder().setTitle('StackBuild API').build()); SwaggerModule.setup('docs', app, doc); await app.listen(process.env.API_PORT ?? 8080); } bootstrap();\n`
  );
  await write(
    root,
    `${b}/src/app.module.ts`,
    `import { Module } from '@nestjs/common'; import { ConfigModule } from '@nestjs/config'; import { HealthController } from './health/health.controller'; import { UsersModule } from './modules/users/users.module'; ${prisma ? "import { DatabaseModule } from './database/database.module';" : ""} ${o.cache === "redis" ? "import { CacheModule } from './cache/cache.module';" : ""} @Module({ imports: [ConfigModule.forRoot({ isGlobal: true }), UsersModule${prisma ? ", DatabaseModule" : ""}${o.cache === "redis" ? ", CacheModule" : ""}], controllers: [HealthController] }) export class AppModule {}\n`
  );
  await write(
    root,
    `${b}/src/health/health.controller.ts`,
    "import { Controller, Get } from '@nestjs/common'; @Controller() export class HealthController { @Get('health') health() { return { success: true, message: 'API is running', data: { status: 'healthy' } }; } @Get('status') status() { return { success: true, message: 'API is running', data: { status: 'healthy' } }; } }\n"
  );
  await write(
    root,
    `${b}/src/modules/users/users.module.ts`,
    `import { Module } from '@nestjs/common'; import { UsersController } from './users.controller'; import { UsersService } from './users.service'; ${prisma ? "import { DatabaseModule } from '../../database/database.module';" : ""} ${o.cache === "redis" ? "import { CacheModule } from '../../cache/cache.module';" : ""} @Module({ imports: [${prisma ? "DatabaseModule" : ""}${prisma && o.cache === "redis" ? ", " : ""}${o.cache === "redis" ? "CacheModule" : ""}], controllers: [UsersController], providers: [UsersService] }) export class UsersModule {}\n`
  );
  await write(
    root,
    `${b}/src/modules/users/users.controller.ts`,
    "import { Controller, Get } from '@nestjs/common'; import { UsersService } from './users.service'; @Controller('users') export class UsersController { constructor(private readonly users: UsersService) {} @Get() list() { return { success: true, message: 'Users retrieved', data: this.users.list() }; } }\n"
  );
  await write(
    root,
    `${b}/src/modules/users/users.service.ts`,
    usersServiceSource(prisma, o.cache === "redis")
  );
  if (prisma) {
    await write(
      root,
      `${b}/src/database/database.module.ts`,
      "import { Global, Module } from '@nestjs/common'; import { PrismaService } from './prisma.service'; @Global() @Module({ providers: [PrismaService], exports: [PrismaService] }) export class DatabaseModule {}\n"
    );
    await write(
      root,
      `${b}/src/database/prisma.service.ts`,
      "import { Injectable } from '@nestjs/common'; import { PrismaClient } from '@prisma/client'; @Injectable() export class PrismaService extends PrismaClient {}\n"
    );
  }
  if (o.cache === "redis") {
    await write(
      root,
      `${b}/src/cache/cache.module.ts`,
      "import { Global, Module } from '@nestjs/common'; import { CacheService } from './cache.service'; @Global() @Module({ providers: [CacheService], exports: [CacheService] }) export class CacheModule {}\n"
    );
    await write(
      root,
      `${b}/src/cache/cache.service.ts`,
      "import { Injectable, OnModuleDestroy } from '@nestjs/common'; import Redis from 'ioredis'; @Injectable() export class CacheService implements OnModuleDestroy { private readonly client = new Redis(process.env.REDIS_URL ?? 'redis://localhost:6379', { lazyConnect: true }); async get<T>(key: string): Promise<T | null> { if (this.client.status === 'wait') await this.client.connect(); const value = await this.client.get(key); return value ? JSON.parse(value) as T : null; } async set(key: string, value: unknown, ttlSeconds = 60) { if (this.client.status === 'wait') await this.client.connect(); await this.client.set(key, JSON.stringify(value), 'EX', ttlSeconds); } async onModuleDestroy() { await this.client.quit(); } }\n"
    );
  }
  await write(
    root,
    `${b}/eslint.config.mjs`,
    "export default [{ ignores: ['dist', 'node_modules'] }];\n"
  );
  for (const f of [
    "common/decorators",
    "common/filters",
    "common/guards",
    "common/interceptors",
    "common/middleware",
    "common/pipes",
    "config",
    "database",
    "modules/users/dto",
    "modules/users/entities",
    "test",
  ])
    await write(root, `${b}/src/${f}/.gitkeep`, "");
  if (prisma)
    await write(
      root,
      `${b}/prisma/schema.prisma`,
      `generator client { provider = "prisma-client-js" }\ndatasource db { provider = "${o.database === "postgres" ? "postgresql" : o.database}" url = env("DATABASE_URL") }\nmodel User { id String @id @default(cuid()); email String @unique; name String; createdAt DateTime @default(now()) }\n`
    );
}
function usersServiceSource(prisma: boolean, cache: boolean): string {
  const imports = `import { Injectable } from '@nestjs/common';${prisma ? " import { PrismaService } from '../../database/prisma.service';" : ""}${cache ? " import { CacheService } from '../../cache/cache.service';" : ""}`;
  const ctor =
    prisma || cache
      ? ` constructor(${prisma ? "private readonly prisma: PrismaService" : ""}${prisma && cache ? ", " : ""}${cache ? "private readonly cache: CacheService" : ""}) {}`
      : "";
  const query = prisma ? "await this.prisma.user.findMany()" : "[]";
  const body = cache
    ? `const cached = await this.cache.get<unknown[]>('users:list'); if (cached) return cached; const users = ${query}; await this.cache.set('users:list', users); return users;`
    : `return ${query};`;
  return `${imports} @Injectable() export class UsersService {${ctor} async list() { ${body} } }\n`;
}
