import type { StackOptions } from '../types.js';
import { FRONTEND_APPS } from '../constants.js';
import { write } from '../utils/filesystem.js';

export async function generateDocker(o: StackOptions): Promise<void> {
  const services: string[] = [];
  for (const app of o.apps.filter(x => FRONTEND_APPS.includes(x))) { const port = o.frontend === 'vite' ? ({ customer: 5173, admin: 5174, partner: 5175 } as Record<string, number>)[app] : ({ customer: 3000, admin: 3001, partner: 3002 } as Record<string, number>)[app]; services.push(`  ${app}:\n    build: ./apps/${app}\n    ports: ["${port}:${port}"]\n    environment:\n      ${o.frontend === 'vite' ? 'VITE_API_URL' : 'NEXT_PUBLIC_API_URL'}: http://localhost:8080\n    restart: unless-stopped`); await write(o.targetDir, `apps/${app}/Dockerfile`, frontendDocker(o, port)); await write(o.targetDir, `apps/${app}/.dockerignore`, 'node_modules\ndist\n.next\n'); }
  services.push(`  api:\n    build: ./apps/api\n    ports: ["8080:8080"]\n    env_file: .env\n    healthcheck:\n      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]\n      interval: 10s\n      timeout: 3s\n      retries: 5\n    restart: unless-stopped`);
  await write(o.targetDir, 'apps/api/Dockerfile', o.backend === 'go' ? 'FROM golang:1.24-alpine AS build\nWORKDIR /app\nCOPY . .\nRUN go build -o api ./cmd/api\nFROM alpine:3.21\nWORKDIR /app\nCOPY --from=build /app/api .\nEXPOSE 8080\nCMD ["./api"]\n' : 'FROM node:22-alpine AS build\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nRUN npm run build\nFROM node:22-alpine\nWORKDIR /app\nCOPY --from=build /app .\nEXPOSE 8080\nCMD ["npm", "run", "start"]\n');
  if (o.database !== 'none') { const image = o.database === 'postgres' ? 'postgres:17-alpine' : o.database === 'mysql' ? 'mysql:8' : 'busybox'; services.push(`  database:\n    image: ${image}\n    ${o.database === 'postgres' ? 'environment:\n      POSTGRES_DB: app\n      POSTGRES_USER: postgres\n      POSTGRES_PASSWORD: postgres\n' : o.database === 'mysql' ? 'environment:\n      MYSQL_DATABASE: app\n      MYSQL_ROOT_PASSWORD: root\n' : ''}    volumes: ["database_data:/data"]\n    restart: unless-stopped`); }
  await write(o.targetDir, 'docker-compose.yml', `services:\n${services.join('\n')}\n${o.database !== 'none' ? '\nvolumes:\n  database_data:\n' : ''}`); await write(o.targetDir, '.dockerignore', 'node_modules\ndist\n.next\n.git\n.env\n');
}
function frontendDocker(o: StackOptions, port: number): string { return o.frontend === 'next' ? `FROM node:22-alpine AS build\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nRUN npm run build\nFROM node:22-alpine\nWORKDIR /app\nCOPY --from=build /app .\nEXPOSE ${port}\nCMD ["npm", "run", "start"]\n` : `FROM node:22-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nEXPOSE ${port}\nCMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]\n`; }
