import path from 'node:path';
import { Command } from 'commander';
import ora from 'ora';
import { collectOptions } from './prompts/options.js';
import { getProjectName } from './prompts/project.js';
import { assertNodeVersion, assertOptionValues, assertTargetDirectory } from './utils/validation.js';
import { generateProject } from './generate.js';
import { log } from './utils/logger.js';
import type { CliOptions } from './types.js';

const program = new Command();
program.name('create-stackbuild').description('Create a production-ready full-stack monorepo').version('0.2.6').argument('[project-name]').option('--preset <preset>').option('--template <template>', 'Alias for --preset').option('--apps <apps>', 'Comma-separated frontend apps for the custom preset').option('--frontend <frontend>').option('--backend <backend>').option('--ui <ui>').option('--database <database>').option('--cache <cache>').option('--package-manager <manager>').option('--go-module <path>').option('--skip-install').option('--no-git').option('--docker').option('--no-docker').option('--force').option('--dry-run', 'Show the generated plan without writing files').option('--debug').action(async (name, raw) => {
  try { assertNodeVersion(); if (raw.preset && raw.template && raw.preset !== raw.template) throw new Error('--preset and --template must use the same value when both are supplied.'); const flags: CliOptions = { preset: raw.preset ?? raw.template, apps: raw.apps?.split(',').map((app: string) => app.trim()).filter(Boolean), frontend: raw.frontend, backend: raw.backend, ui: raw.ui, database: raw.database, cache: raw.cache, packageManager: raw.packageManager, goModule: raw.goModule, docker: raw.docker, git: raw.git, install: !raw.skipInstall, force: raw.force, dryRun: raw.dryRun, debug: raw.debug }; assertOptionValues(flags); if (process.stdout.isTTY && !flags.dryRun) log.logo(); const projectName = await getProjectName(name); const targetDir = path.resolve(process.cwd(), projectName); if (!flags.dryRun) await assertTargetDirectory(targetDir, flags.force ?? false); const options = await collectOptions(projectName, targetDir, flags); if (flags.dryRun) { log.title('StackBuild dry run'); console.log(`  Target: ${targetDir}\n  Apps: ${options.apps.join(', ')}\n  Frontend: ${options.frontend}\n  Backend: ${options.backend}\n  UI: ${options.ui}\n  Database: ${options.database}\n  Cache: ${options.cache}\n  Package manager: ${options.packageManager}\n  Docker: ${options.docker ? 'yes' : 'no'}\n  Install dependencies: ${options.install ? 'yes' : 'no'}`); return; } const spinner = ora('Generating StackBuild project…').start(); await generateProject(options); spinner.succeed('StackBuild project created successfully.'); log.title('Next steps'); console.log(`  cd ${projectName}\n  ${options.install ? `${options.packageManager === 'npm' ? 'npm run dev' : `${options.packageManager} dev`}` : `${options.packageManager} install\n  ${options.packageManager === 'npm' ? 'npm run dev' : `${options.packageManager} dev`}`}`); log.info(`\nApps: ${options.apps.join(', ')} · API: http://localhost:8080/health`); } catch (error) { log.error(error instanceof Error ? error.message : String(error)); if (raw.debug && error instanceof Error) console.error(error.stack); process.exitCode = 1; }
});
program.parseAsync().catch(error => { log.error(error.message); process.exitCode = 1; });
